CREATE DATABASE IF NOT EXISTS LAUP DEFAULT CHARACTER SET utf8;
SET NAMES 'utf8';
USE LAUP;

CREATE TABLE TOKENS (
  id INT NOT NULL AUTO_INCREMENT COMMENT '唯一ID',
  token VARCHAR(128) NOT NULL COMMENT 'token',
  um VARCHAR(128) NOT NULL COMMENT 'token对应的um',
  expire_time DATETIME NOT NULL COMMENT 'token过期时间',
  PRIMARY KEY (id),
  KEY (token)
) ENGINE = INNODB;


CREATE TABLE ROLE_INFO (
  id INT NOT NULL AUTO_INCREMENT COMMENT '唯一ID',
  um VARCHAR(128) NOT NULL COMMENT 'Token对应的um账号',
  role VARCHAR(128) NOT NULL COMMENT '角色: ADMIN',
  PRIMARY KEY(id)
) ENGINE = INNODB;

